name: CI

on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy to production
    
    steps:
    - uses: actions/npm@master
    - name: Clean install dependencies and build
      run: |
        npm ci
        npm run build
    - uses: natemoo-re/action-firebase@master
    - name: Deploy to firbase hosting
      run: deploy --token ${{ secrets.FIREBASE_CI }}
